name: Golang Docker Build

on:
  push:

env:
  CONTAINER_REPOSITORY: quay.io/snowyxa
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login using secrets
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: snowyxa+gitactions
          password: AAXD8F8FV1L745210X7VR6DDF5M54161OTEZ3V3IGNQT5N5CLPSGSJOYEGLNKGM0

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: quay.io/snowyxa/alm-workshop

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: quay.io/snowyxa/alm-workshop:latest
